config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :lists do
    get "/shopping", to: "lists#shopping"
    resources :categories, only: [:create] do 
      resources :items, only: [:create]
    end
  end
  resources :items, only: [:update, :destroy]
  resources :categories, only: [:update, :destroy]
  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :lists do
        resources :categories, only: [:create] do
          resources :items, only: [:create]
        end
      end
      resources :items, only: [:update, :destroy]
      resources :categories, only: [:update, :destroy]
    end
  end
end

app/models/list.rb
class List < ApplicationRecord
  belongs_to :user
  has_many :categories, dependent: :destroy

  validates :name, presence: true

  def no_name
    self.name = "my list" if self.name.empty?
  end

  def default_cat
    cat = Category.new(category_name: "My List")
    cat.list_id = self.id
    cat.save
  end
end

app/controllers/api/v1/lists_controller.rb
class Api::V1::ListsController < Api::V1::BaseController
  before_action :set_list, only: [:show, :update, :destroy]
  def index
    @lists = policy_scope(List)
    authorize @lists
  end

  def show
  end

  def create
    @list = List.new(list_params)
    @list.user = current_user
    @list.no_name
    authorize @list

    if @list.save
      redirect_to api_v1_lists_path
    else
      render_error
    end
  end

  def update
    @list.update(list_params)
    @list.no_name
    if @list.save
      redirect_to api_v1_lists_path
    else
      render_error
    end
  end

  def destroy
    @list.destroy
    redirect_to api_v1_lists_path
  end

  private

  def set_list
    @list = List.find(params[:id])
    authorize @list
  end

  def list_params
    params.require(:list).permit(:name, :user_id)
  end

  def render_error
    render json: { errors: @list.errors.full_messages },
      status: :unprocessable_entity
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: [:show, :update, :destroy]

  def index
    ## display this list with the latest list at the top
    @lists = List.all
    

    ## TODO: Add a new list
    @list = List.new
  end

  def show
    # categories saved into variable and sorted by created at
    @categories = @list.categories.sort_by(&:created_at)

    # TODO: Add category
    @last_id = Category.last.id

    @category = Category.new
    @item = Item.new

    # Find all cattegories where the list == list_id
    # @categories = Category.where(id: list_id)
  end

  def shopping
    @list = List.find(params[:list_id])

    # only saves categories that have at least one item.
    @categories = @list.categories.select {|category| category.items.length > 0 }
  end

  def create
    @list = List.new(list_params)
    @list.user = current_user

    # @list.name = "BOOOO" if @list.name.empty?

    @list.no_name

    if @list.save!
      @list.default_cat
      redirect_to lists_path
    else
      render :new
    end
  end

  def update
    @list.update(list_params)
    @list.no_name
    if @list.save
      redirect_to lists_path
    else
      render :index
    end
  end

  def destroy
    @list.destroy

    redirect_to lists_path
  end

  private

  def list_params
    params.require(:list).permit(:name, :user_id)
  end

  def set_list
    @list = List.find(params[:id])
  end
end

app/views/lists/index.html.erb
<%= render 'shared/navbar' %>
<br> <br> <br>

<div class="lists-container">
  <button type="button" class="btn-long list-button-flex" data-toggle="modal" data-target="#addListModal">
    <i class="fas fa-plus"></i>
    <h2>list</h2>
  </button>

  <% @lists.each do |list|%>
  <div class="list-item">
    <div>
      <h1>
        <i class="far fa-star"></i>
        <%= link_to list.name, list_path(list) %>
        <!-- should we still pull the date forward for the time of creation of a new list -->
        <span style="font-size: 14px; color: #85a1b3;"> <%= list.created_at.strftime("%-d/%m/%y") %> </span>
      </h1>
    </div>
      <div class="icon-group ">
          <%= link_to "", list_path(list), method: :delete, data: { confirm: "Are you quite sure?" }, class:"fas fa-trash" %>
          <a type="button" class="fas fa-pen" data-toggle="modal" data-target="#editListName<%= list.id %>">
          </a>
      </div>
  </div>

  <div id="editListName<%= list.id %>" class="modal fade" tabindex="-1" role="dialog">
    <div class="modal-dialog modal-dialog-centered" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title">edit list name</h5>
        </div>
        <div class="modal-body">
          <%= simple_form_for(list) do |f| %>
          <%= f.input :name, label: false %>
        </div>
        <div class="modal-footer">
          <%= f.submit "edit name", class: "btn btn-flat" %>
          <% end %>
        </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

<div id="addListModal" class="modal fade" tabindex="-1" role="dialog">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">name your list</h5>
        </button>
      </div>
      <div class="modal-body">
        <%= simple_form_for(@list) do |f| %>
        <%= f.input :name, label: false %>
      </div>
      <div class="modal-footer">
        <%= f.submit "add list", class: "btn btn-flat" %>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/lists/shopping.html.erb
<div class="navbar">
  <%= link_to "", list_path(@list), class:"fas fa-arrow-left" %>
  <div class="app-name">
    <p>checkitoff</p>
  </div>
  <%= link_to "log out", destroy_user_session_path, method: :delete, class: "btn-small" %>
</div>
<br><br><br>
<div class="shopping-container">
  <% @categories.each do |category| %>
    <h2 class="shopping-category" style="background-color:<%= category.category_color %>;"><%= category.category_name %></h2>
    <div class="item-shopping">
    <% items_sorted = category.items.sort_by {|item| item.created_at } %>
      <% items_sorted.each do |item| %>

        <div class="category-item-container" 
             id="item-id-<%= item.id %>" data-id="<%= item.id %>" 
             data-color="<%= category.category_icon %>"
             data-selected="<%= item.item_selected %>"
             style="background-color: <%= category.category_icon %>">

          <div class="item-list">
            <i id="circle-<%= item.id %>" class="far fa-circle"></i>
            <span><%= item.item_name %> </span>
          </div> 
        </div>

      <% end %>
    </div>
  <% end  %>

  <div class="button-container">
    <%= link_to "edit list", list_path(@list), class:"btn-long-half" %>
    <%= link_to "done", lists_path(@lists), class:"btn-long-half ml-2"  %>
  </div>
</div>

app/views/lists/show.html.erb
<div class="navbar">
  <%= link_to "", lists_path, class:"fas fa-arrow-left" %>
  <div class="app-name">
    <p>checkitoff</p>
  </div>
  <%= link_to "log out", destroy_user_session_path, method: :delete, class: "btn-small" %>
</div>
<br><br><br>
<div id="data-id" data-id="<%= @list.id %>" data-lastid="<%= @last_id %>"></div>
<div class="category-container">
  <div class="margin-container-scroll">
      <button type="button" id="modalBtn" class="btn-long list-button-flex ">
    <i class="fas fa-plus"></i>
    <h2>category</h2>
  </button>

  <% @categories.each do |category| %>
  <div class="category-item" style="background-color:<%= category.category_color %>;">
    <div class="category-title">
      <h2> <%= category.category_name %> </h2>
    </div>
    <div class="icon-group-cat">
      <% if category.category_name != "My List" %>
      <%= link_to "", category_path(category), method: :delete, data: { confirm: "Are you quite sure?" }, class:"fas fa-trash" %>
      <% end %>
    </div>
  </div>

   <% category.items.each do |item| %>
    <div class="item-input" style="background-color:<%= category.category_icon %>;">
      <div id="item-wrapper-<%= item.id %>">
          <div class="item-stuff">
              <i class="far fa-circle"></i>
              <p> <%= item.item_name %> </p>
            <div data-id="<%= item.id %>" class="icon-group-item">
              <%= link_to "", item_path(item), method: :delete, class:"fas fa-trash" %>
              <a id="edit-item-<%= item.id %>" class="fas fa-pen"></a>
            </div>
          </div>
      </div>


      <div id="edit-form-<%= item.id %>" class="hidden">
        <div class="flexbox-class">
          <%= simple_form_for(item) do |f| %>
           <%= f.input :item_name, label: false %>
           <%= f.submit "edit item", class:"hide-edit" %>
          <% end %>
        </div>
      </div>
    </div>
      <% end %>
     <div id="addItem-<%= category.id %>" data-id="<%= category.id %>" class="item-add">
        <p>
          <i class="fas fa-plus"></i>
          add another item
        </p>
      </div>
      <div class="input-box hidden" id="input-box-<%= category.id %>">
        <div class="add-form">
          <%= simple_form_for([@list, category, @item]) do |f| %>
            <%= f.input :item_name, label: false, placeholder: "item name" %>
            <%= f.submit "add item", id:"submit-item-#{category.id}", class:"add-item-form" %>
          <% end %>
        </div>

      </div>

<% end %>
  </div>


  <div >
    <%= link_to "go shopping", list_shopping_path(@list), class: 'btn btn-long-shop'%>
  </div>

</div>

<div id="categoryModal" class="classCategoryModal">
  <div class="category-modal-content">
    <div class="category_cards">
      <div class="category_card" id="meat_fish">
        <i class="fas fa-drumstick-bite"></i>
        <h1>meat & fish</h1>
      </div>
      <div class="category_card" id="fruit_veg">
        <i class="fas fa-seedling"></i>
        <h1>fruit & veg</h1>
      </div>
      <div class="category_card" id="snacks">
        <i class="fas fa-cookie-bite"></i>
        <h1>snacks</h1>
      </div>
      <div class="category_card" id="soft_drinks">
        <i class="fas fa-glass-whiskey"></i>
        <h1>soft drinks</h1>
      </div>
      <div class="category_card" id="beer_wine">
        <i class="fas fa-wine-bottle"></i>
        <h1>beer & wine</h1>
      </div>
      <div class="category_card" id="household">
        <i class="fas fa-home"></i>
        <h1>household</h1>
      </div>
      <div class="category_card" id="health">
        <i class="fas fa-heart"></i>
        <h1>health</h1>
      </div>
      <div class="category_card" id="beauty">
        <i class="fas fa-pump-soap"></i>
        <h1>beauty</h1>
      </div>
      <div class="category_card" id="bakery">
        <i class="fas fa-bread-slice"></i>
        <h1>bakery</h1>
      </div>
      <div class="category_card" id="deli">
        <i class="fas fa-cheese"></i>
        <h1>deli</h1>
      </div>
      <div class="category_card" id="frozen">
        <i class="far fa-snowflake"></i>
        <h1>frozen</h1>
      </div>
      <div class="category_card" id="petfood">
        <i class="fas fa-paw"></i>
        <h1>petfood</h1>
      </div>
      <div class="category_card" id="toys">
        <i class="fas fa-gamepad"></i>
        <h1>toys</h1>
      </div>
      <div class="category_card" id="clothes">
        <i class="fas fa-tshirt"></i>
        <h1>clothes</h1>
      </div>
      <div class="category_card" id="stationary">
        <i class="fas fa-paperclip"></i>
        <h1>stationary</h1>
      </div>
    </div>
  </div>
</div>